### ISSUE TITLE
Aresite2 (v0.1.2) assumes default python version is python3 

### ISSUE THREAD

**Issue by borauyar** [bgruening/galaxytools#629]
In the aresite2.xml tool description file, the aresite2.py script is called like this: 
`python aresite2.py -g 'cxcl2' -m 'ATTTA' -s 'Homo_sapiens' >log.out`

Some of the imported modules are urllib.request, urllib.parse, urllib.error, which are not available in python2 but only available in python3. When python3 is not available, it gives this error:

> Traceback (most recent call last):
  File "/data/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/rnateam/aresite2/138ff4068d27/aresite2/aresite2.py", line 7, in <module>
    import urllib.request, urllib.parse, urllib.error
ImportError: No module named request

Replacing the 'python' call with a path to python3 in the aresite.py script fixes the issue. 
I think it should be somehow clarified that python3 is required for this script.

**Comment by bgruening** [comment]
@borauyar requests should be available for python2 as well: https://anaconda.org/conda-forge/requests/files
However, it can be that this tool is only running under python3 for other reasons that I don't know and that we did not catched because all newer Galaxy/Conda dependencies are running with python3. If this is the case please add `<requirement type="package" version="3.4">python</requirement>` to https://github.com/bgruening/galaxytools/blob/master/tools/rna_tools/aresite2/aresite2.xml#L4 ... this should be the correct fix.

ping @jfallmann - its his baby :)

**Comment by jfallmann** [comment]
@borauyar @bgruening Thanks for finding and fixing this, I was not aware this does not work with python2, also thought it should be compatible, however python 3 is now a requirement

**Comment by borauyar** [comment]
@jfallmann @bgruening perfect, thanks!

**Comment by nsoranzo** [comment]
Re-adding support for Python2 may be just a matter of use `six.moves` for imports.
